# Generated by Django 3.2.8 on 2021-12-02 10:38

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('imagen', cloudinary.models.CloudinaryField(blank=True, default='', max_length=255, null=True, verbose_name='imagen')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=20)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FormaPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('portada', cloudinary.models.CloudinaryField(blank=True, default='', max_length=255, null=True, verbose_name='Portada')),
                ('logo', cloudinary.models.CloudinaryField(blank=True, default='', max_length=255, null=True, verbose_name='Logo')),
                ('telefono', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=200)),
                ('fechaHora', models.DateTimeField(auto_now=True)),
                ('totalPagar', models.DecimalField(decimal_places=2, max_digits=9)),
                ('montoPago', models.DecimalField(decimal_places=2, max_digits=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='bikeshop.cliente')),
                ('formaPago', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='bikeshop.formapago')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('imagen1', cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='Imagen 1')),
                ('imagen2', cloudinary.models.CloudinaryField(blank=True, default='', max_length=255, null=True, verbose_name='Imagen 2 (optional)')),
                ('imagen22', cloudinary.models.CloudinaryField(blank=True, default='', max_length=255, null=True, verbose_name='Imagen 22 (optional)')),
                ('imagen3', cloudinary.models.CloudinaryField(blank=True, default='', max_length=255, null=True, verbose_name='Imagen 3 (optional)')),
                ('imagen33', cloudinary.models.CloudinaryField(blank=True, default='', max_length=255, null=True, verbose_name='Imagen 33 (optional)')),
                ('videourl', models.URLField(blank=True, default='', null=True)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=9)),
                ('serie', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True)),
                ('dimensiones', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('color', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('material', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('fabricacion', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='bikeshop.categoria')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='bikeshop.marca')),
            ],
        ),
        migrations.CreateModel(
            name='PedidoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=9)),
                ('cantidad', models.IntegerField(default=1)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='bikeshop.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='bikeshop.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estrellas', models.PositiveSmallIntegerField(default=1)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='bikeshop.cliente')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='bikeshop.producto')),
            ],
        ),
    ]
